### PR TITLE
Linux: Update stale dependency for libpng, fix README.md

### PR DESCRIPTION
**Pull request by yaynstuff**
This fixes the stale dependency now that the libpng 3p has been fixed

### CODE REVIEW

**Review by bennettgoble — APPROVED** [review]
LGTM, thanks @yaynstuff

**Comment by bennettgoble** [comment]
@yaynstuff can you pull in the latest changes from master? It doesn't look like this repo was set up to build PRs. (Fixed in #7 )

**Comment by yaynstuff** [comment]
> @yaynstuff can you pull in the latest changes from master? It doesn't look like this repo was set up to build PRs. (Fixed in #7 )

Hello - Did you mean sync my fork of this repo (I did this just now) or have I misunderstood what you meant?

**Comment by bennettgoble** [comment]
@yaynstuff yep, that was what I needed to be able to run builds. All green, merged.

**Comment by yaynstuff** [comment]
Hello - Could v2.12.1.c669252 please be made "latest" release please? When visiting the page for this 3p, the build from 2023 is still considered "latest"

**Comment by bennettgoble** [comment]
@yaynstuff v2.12.1.c669252 has been marked as latest.

**Comment by bennettgoble** [comment]
Ah, actually --it looks like this repository was missing build triggers for tags. This has been fixed and I've kicked off a release for https://github.com/secondlife/3p-freetype/releases/tag/v2.12.1.d315c1b

**Pull request merged**
